addr      = "http://localhost:1313/alt/"
brand     = "bdsr"
title     = "B.USOC Data Storage Report"
author    = "BUSOC"
canonical = true

[[menu]]
label = "ASIM"
link  = "#"
menu  = [
  {label = "DHPU", link=""},
  {label = "MMIA", link=""},
  {label = "MXGS", link=""},
]

[[menu]]
label = "SOLAR"
link  = "#"

[[menu]]
label = "FSL"
link  = "#"

[[menu]]
label = "PCDF"
link  = "#"

[[data]]
location = "list.csv"
template = "list"
url      = "/"

[[data]]
location = "941"
title    = "PCDF"
template = "report"

[[data]]
location = "943"
title    = "PCDF"
template = "report"

[[data]]
location = "620"
title    = "RESPONSE"
template = "report"
copy     = true

[[data]]
location = "906"
title    = "DHPU"
template = "report"
copy     = true

[[data]]
location = "907"
title    = "MMIA"
template = "report"
copy     = true

[[data]]
location = "908"
title    = "MXGS"
template = "report"
copy     = true
